version: '2'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "127.0.0.1:2181:2181"
    environment:
       ZOO_MY_ID: 1
       ZOO_SERVERS: server.1=zookeeper:2888:3888
  kafka:
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock